# Generated by Django 3.2.2 on 2021-05-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinfo',
            name='email',
            field=models.CharField(blank=True, max_length=256, unique=True, verbose_name='Email'),
        ),
    ]
